# Generated by Django 3.2.7 on 2021-09-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('subject_image', models.ImageField(blank=True, upload_to='subjectimages')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='authuser.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no. ')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('lesson_video', models.FileField(blank=True, upload_to='subjectimages')),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='subjectimages')),
                ('ppt', models.FileField(blank=True, upload_to='subjectimages', verbose_name='Presentations')),
                ('notes', models.FileField(blank=True, upload_to='subjectimages')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='authuser.subject')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
