# Generated by Django 3.2.7 on 2021-09-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_lesson_standard_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
